/*
 * BanksElView.java
 *
 * Created on 01.08.2011, 14:44:07
 */
package sales.catalogs;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import org.hibernate.classic.Session;
import org.jdesktop.application.Action;
import sales.SalesApp;
import sales.SalesView;
import sales.entity.Banks;
import sales.interfaces.IClose;
import sales.util.HUtil;
import sales.util.Util;

public class BanksElView extends JInternalFrame implements IClose {

    static Logger logger = Logger.getLogger(SalesApp.class.getName());

    public BanksElView(SalesView salesView, BanksView parent, Integer elementCode) {
        initComponents();

        Util.initJIF(this, "Банк", parent, salesView);

        this.salesView = salesView;
        this.parent = parent;
        this.elementCode = elementCode;

        Session session = HUtil.getSession();
        Banks b = null;
        if (elementCode != null) {
            b = (Banks) HUtil.getElement("Banks", elementCode, session);
        }

        if (b != null) {
            jlCode.setText("Код: " + b.getCode());
            jtfName.setText(b.getName());
            jtaAddress.setText(b.getAddress());
            jtfBankCode.setText(b.getBankCode());
            jtfUnt.setText(b.getUnt());
            lock = b.getLocked();
            if (lock == 1) {
                JOptionPane.showMessageDialog(
                        this,
                        "Элемент редактируется другим пользователем и будет открыт только для просмотра!",
                        "Блокировка", JOptionPane.PLAIN_MESSAGE);
                jtfBankCode.setEditable(false);
                jtfName.setEditable(false);
                jtaAddress.setEditable(false);
                jtfUnt.setEditable(false);
            } else {
                session.beginTransaction();
                b.setLocked(1);
                session.merge(b);
                session.getTransaction().commit();
            }
        } else {
            jlCode.setText("Код: " + HUtil.getNextMax("Banks", "code", session));
            lock = 0;
        }
        session.close();

        if(b != null) {
            hash = Util.hash(this);
        } else {
            hash = null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfBankCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAddress = new javax.swing.JTextArea();
        jbClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfUnt = new javax.swing.JTextField();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sales.SalesApp.class).getContext().getResourceMap(BanksElView.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jlCode.setText(resourceMap.getString("jlCode.text")); // NOI18N
        jlCode.setName("jlCode"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jtfName.setText(resourceMap.getString("jtfName.text")); // NOI18N
        jtfName.setName("jtfName"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jtfBankCode.setText(resourceMap.getString("jtfBankCode.text")); // NOI18N
        jtfBankCode.setName("jtfBankCode"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jtaAddress.setColumns(20);
        jtaAddress.setFont(resourceMap.getFont("jtaAddress.font")); // NOI18N
        jtaAddress.setRows(5);
        jtaAddress.setName("jtaAddress"); // NOI18N
        jScrollPane1.setViewportView(jtaAddress);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sales.SalesApp.class).getContext().getActionMap(BanksElView.class, this);
        jbClose.setAction(actionMap.get("closeEl")); // NOI18N
        jbClose.setText(resourceMap.getString("jbClose.text")); // NOI18N
        jbClose.setName("jbClose"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jtfUnt.setText(resourceMap.getString("jtfUnt.text")); // NOI18N
        jtfUnt.setName("jtfUnt"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCode, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBankCode, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfUnt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(jbClose))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCode)
                    .addComponent(jLabel4)
                    .addComponent(jtfBankCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfUnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jbClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbClose;
    private javax.swing.JLabel jlCode;
    private javax.swing.JTextArea jtaAddress;
    private javax.swing.JTextField jtfBankCode;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfUnt;
    // End of variables declaration//GEN-END:variables
    private SalesView salesView;
    private BanksView parent;
    private Integer elementCode;
    private Integer lock;
    private Integer hash;

    private void save() {

        try {
            Session session = HUtil.getSession();
            Banks b = (Banks) HUtil.getElement("Banks", elementCode, session);
            session.beginTransaction();
            if (b == null) {
                b = new Banks();
                b.setName(jtfName.getText());
                b.setAddress(jtaAddress.getText());
                b.setBankCode(jtfBankCode.getText());
                b.setUnt(jtfUnt.getText());
                b.setLocked(0);
                session.save(b);
            } else {
                b.setName(jtfName.getText());
                b.setAddress(jtaAddress.getText());
                b.setBankCode(jtfBankCode.getText());
                b.setUnt(jtfUnt.getText());
                b.setLocked(0);
                session.merge(b);
            }
            session.getTransaction().commit();
            session.close();
            Util.updateJournals(salesView, BanksView.class);
        } catch (Exception e) {
            logger.error(e);
        }
    }

    public void close() {

        if (lock == 0) {
            if (hash == null || !hash.equals(Util.hash(this))) {
                int a = JOptionPane.showOptionDialog(
                        this, "Сохранить элемент?", "Сохранение", JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Да", "Нет"}, "Да");
                if (a == 0) {
                    save();
                }
            }
            Session session = HUtil.getSession();
            Banks b = (Banks) HUtil.getElement("Banks", elementCode, session);
            if (b != null && lock == 0) {
                session.beginTransaction();
                b.setLocked(0);
                session.merge(b);
                session.getTransaction().commit();
            }
            session.close();
        }
    }

    @Action
    public void closeEl() {
        close();
        Util.closeJIF(this, parent, salesView);
        Util.closeJIFTab(this, salesView);
    }
}
