/*
 * jifNomenclature.java
 *
 * Created on 06.05.2011, 12:51:06
 */
package sales.catalogs;

import java.awt.Component;
import java.util.List;
import java.util.Vector;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.text.JTextComponent;
import org.apache.log4j.Logger;
import org.hibernate.classic.Session;
import org.jdesktop.application.Action;
import sales.SalesApp;
import sales.SalesView;
import sales.entity.Banks;
import sales.entity.Suppliers;
import sales.interfaces.IClose;
import sales.interfaces.IJournal;
import sales.interfaces.ISupplier;
import sales.util.HUtil;
import sales.util.Util;

public class SuppliersView extends javax.swing.JInternalFrame implements IClose, IJournal {

    static Logger logger = Logger.getLogger(SalesApp.class.getName());

    public SuppliersView(SalesView salesView, ISupplier parent) {

        initComponents();

        Util.initJIF(this, "Поставщики", parent, salesView);
        Util.initJTable(jtSuppliers);

        this.salesView = salesView;
        this.parent = parent;

        if (parent == null) {
            jbOK.setVisible(false);
        }

        filter = "";

        showTable();

        Util.setMoveRight(jtSuppliers);

        trash = false;
    }

    private class MyTableModel extends DefaultTableModel {

        public MyTableModel(Vector table, Vector header) {
            super(table, header);
        }

        @Override
        public boolean isCellEditable(int r, int c) {
            return false;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspNomenclature = new javax.swing.JScrollPane();
        jtSuppliers = new javax.swing.JTable() {

            public Component prepareEditor(TableCellEditor editor,int row,int col)
            {
                Component c = super.prepareEditor(editor, row, col);
                if (c instanceof JTextComponent) {
                    ((JTextComponent) c).selectAll();
                    SwingUtilities.invokeLater(new Util.SelectLater((JTextComponent) c));
                }
                return c;
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jtfFilter = new javax.swing.JTextField();
        jbAddItem = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbOK = new javax.swing.JButton();
        jbClose = new javax.swing.JButton();
        jbTrash = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sales.SalesApp.class).getContext().getResourceMap(SuppliersView.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jspNomenclature.setName("jspNomenclature"); // NOI18N

        jtSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtSuppliers.setFillsViewportHeight(true);
        jtSuppliers.setName("jtSuppliers"); // NOI18N
        jtSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtSuppliersMouseClicked(evt);
            }
        });
        jspNomenclature.setViewportView(jtSuppliers);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jtfFilter.setText(resourceMap.getString("jtfFilter.text")); // NOI18N
        jtfFilter.setName("jtfFilter"); // NOI18N
        jtfFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFilterKeyReleased(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sales.SalesApp.class).getContext().getActionMap(SuppliersView.class, this);
        jbAddItem.setAction(actionMap.get("addItem")); // NOI18N
        jbAddItem.setText(resourceMap.getString("jbAddItem.text")); // NOI18N
        jbAddItem.setName("jbAddItem"); // NOI18N

        jbDelete.setAction(actionMap.get("deleteItem")); // NOI18N
        jbDelete.setText(resourceMap.getString("jbDelete.text")); // NOI18N
        jbDelete.setName("jbDelete"); // NOI18N

        jbOK.setAction(actionMap.get("OK")); // NOI18N
        jbOK.setText(resourceMap.getString("jbOK.text")); // NOI18N
        jbOK.setName("jbOK"); // NOI18N

        jbClose.setAction(actionMap.get("closeCat")); // NOI18N
        jbClose.setText(resourceMap.getString("jbClose.text")); // NOI18N
        jbClose.setName("jbClose"); // NOI18N

        jbTrash.setAction(actionMap.get("showTrash")); // NOI18N
        jbTrash.setText(resourceMap.getString("jbTrash.text")); // NOI18N
        jbTrash.setName("jbTrash"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jspNomenclature, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jbAddItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbTrash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                        .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspNomenclature, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddItem)
                    .addComponent(jbDelete)
                    .addComponent(jbClose)
                    .addComponent(jbOK)
                    .addComponent(jbTrash))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtSuppliersMouseClicked
        if (evt.getClickCount() > 1) {
            if (jtSuppliers.columnAtPoint(evt.getPoint()) == 0 && parent != null) {
                OK();
            } else {
                openEl();
            }
        }
    }//GEN-LAST:event_jtSuppliersMouseClicked

    private void jtfFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFilterKeyReleased
        filter = Util.getFilter(jtfFilter.getText(), new String[]{"name", "address", "account"});
        showTable();
}//GEN-LAST:event_jtfFilterKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAddItem;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbOK;
    private javax.swing.JButton jbTrash;
    private javax.swing.JScrollPane jspNomenclature;
    private javax.swing.JTable jtSuppliers;
    private javax.swing.JTextField jtfFilter;
    // End of variables declaration//GEN-END:variables
    private SalesView salesView;
    private ISupplier parent;
    private List table;
    private String filter;
    private boolean trash;

    public void showTable() {
        Session session = HUtil.getSession();
        String delStr = "x.active = 0";
        if (trash) {
            delStr = "x.active = 2";
        }
        table = HUtil.executeHql("from Suppliers x where " + delStr + filter + " order by x.code");
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Код");
        tableHeaders.add("Наименование");
        tableHeaders.add("Юр.адрес");
        tableHeaders.add("Банк");
        tableHeaders.add("Рас.счет");
        tableHeaders.add("УНН");

        if (table != null) {
            for (int i = 0; i < table.size(); i++) {
                Suppliers s = (Suppliers) table.get(i);
                Vector<Object> oneRow = new Vector<Object>();
                oneRow.add(s.getCode());
                oneRow.add(s.getName());
                oneRow.add(s.getAddress());
                Banks b = (Banks) HUtil.getElement("Banks", s.getBank(), session);
                if (b != null) {
                    oneRow.add(b.getName());
                } else {
                    oneRow.add("");
                }
                oneRow.add(s.getAccount());
                oneRow.add(s.getUnt());
                tableData.add(oneRow);
            }
        }

        session.close();

        jtSuppliers.setModel(new MyTableModel(tableData, tableHeaders));
        Util.autoResizeColWidth(jtSuppliers);
        jtSuppliers.getColumnModel().getColumn(0).setMinWidth(40);
        jtSuppliers.getColumnModel().getColumn(0).setMaxWidth(40);
        jtSuppliers.getColumnModel().getColumn(1).setMinWidth(200);
        jtSuppliers.getColumnModel().getColumn(2).setMinWidth(200);

    }

    @Action
    public void addItem() {
        JInternalFrame doc = new SuppliersElView(salesView, this, null);
        salesView.getJDesktopPane().add(doc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        doc.setVisible(true);
        try {
            doc.setSelected(true);
        } catch (Exception e) {
            logger.error(e);
        }
    }

    @Action
    public void deleteItem() {
        if (!trash) {
            int r = jtSuppliers.getSelectedRow();
            if (r != -1) {
                int a = JOptionPane.showOptionDialog(
                        this, "Удалить элемент " + ((Suppliers) table.get(r)).getName() + "?", "Удаление", JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, new Object[]{
                            "Да", "Нет"}, "Нет");
                if (a == 0) {
                    changeDelStatus(2, r);
                }
            }
        } else {
            int r = jtSuppliers.getSelectedRow();
            if (r != -1) {
                int a = JOptionPane.showOptionDialog(
                        this, "Восстановить элемент " + ((Suppliers) table.get(r)).getName() + " из корзины?", "Восстановление", JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, new Object[]{
                            "Да", "Нет"}, "Нет");
                if (a == 0) {
                    changeDelStatus(0, r);
                }
            }
        }
    }

    @Action
    public void OK() {
        TableCellEditor tce = jtSuppliers.getCellEditor();
        if (tce != null) {
            tce.stopCellEditing();
        }
        if (parent != null && jtSuppliers.getSelectedRow() != -1) {
            parent.setSupplier(
                    new Integer(jtSuppliers.getModel().getValueAt(jtSuppliers.getSelectedRow(), 0).toString()));
        }
        closeCat();
    }

    public void close() {
    }

    @Action
    public void closeCat() {
        Util.closeJIF(this, parent, salesView);
        Util.closeJIFTab(this, salesView);
    }

    private void changeDelStatus(int status, int r) {
        try {
            Session session = HUtil.getSession();
            session.beginTransaction();
            Suppliers el = (Suppliers) HUtil.getElement("Suppliers", ((Suppliers) table.get(r)).getCode(), session);
            if (el != null) {
                el.setActive(status);
                session.save(el);
            }
            session.getTransaction().commit();
            session.close();
        } catch (Exception e) {
            logger.error(e);
        }
        showTable();
    }

    @Action
    public void showTrash() {
        if (!trash) {
            jbDelete.setText("Восстановить");
            jbTrash.setText("Журнал");
            trash = true;

        } else {
            jbDelete.setText("Удалить");
            jbTrash.setText("Корзина");
            trash = false;
        }
        showTable();
    }

    private void openEl() {
        int r = jtSuppliers.getSelectedRow();
        if (r != -1) {
            JInternalFrame doc =
                    new SuppliersElView(salesView, this, ((Suppliers) table.get(r)).getCode());
            salesView.getJDesktopPane().add(doc, javax.swing.JLayeredPane.DEFAULT_LAYER);
            doc.setVisible(true);
            try {
                doc.setSelected(true);
            } catch (Exception e) {
                logger.error(e);
            }
        }
    }
}
