package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA



/**
 * Banks generated by hbm2java
 */
public class Banks  implements java.io.Serializable {


     private Integer code;
     private String name;
     private String address;
     private String unt;
     private String bankCode;
     private int locked;
     private int active;

    public Banks() {
    }

	
    public Banks(int locked, int active) {
        this.locked = locked;
        this.active = active;
    }
    public Banks(String name, String address, String unt, String bankCode, int locked, int active) {
       this.name = name;
       this.address = address;
       this.unt = unt;
       this.bankCode = bankCode;
       this.locked = locked;
       this.active = active;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getUnt() {
        return this.unt;
    }
    
    public void setUnt(String unt) {
        this.unt = unt;
    }
    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }
    public int getLocked() {
        return this.locked;
    }
    
    public void setLocked(int locked) {
        this.locked = locked;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


