package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA



/**
 * Constants generated by hbm2java
 */
public class Constants  implements java.io.Serializable {


     private Integer code;
     private String name;
     private String fullName;
     private String value;

    public Constants() {
    }

    public Constants(String name, String fullName, String value) {
       this.name = name;
       this.fullName = fullName;
       this.value = value;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


