package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer code;
     private String name;
     private String shortName;
     private String occupation;
     private String passportNumber;
     private String passportDatePlace;
     private int active;

    public Employee() {
    }

	
    public Employee(int active) {
        this.active = active;
    }
    public Employee(String name, String shortName, String occupation, String passportNumber, String passportDatePlace, int active) {
       this.name = name;
       this.shortName = shortName;
       this.occupation = occupation;
       this.passportNumber = passportNumber;
       this.passportDatePlace = passportDatePlace;
       this.active = active;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public String getPassportNumber() {
        return this.passportNumber;
    }
    
    public void setPassportNumber(String passportNumber) {
        this.passportNumber = passportNumber;
    }
    public String getPassportDatePlace() {
        return this.passportDatePlace;
    }
    
    public void setPassportDatePlace(String passportDatePlace) {
        this.passportDatePlace = passportDatePlace;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


