package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA



/**
 * Inventorytable generated by hbm2java
 */
public class Inventorytable  implements java.io.Serializable {


     private Integer code;
     private int documentCode;
     private int line;
     private int productCode;
     private int price;
     private int quantity;
     private int newQuantity;

    public Inventorytable() {
    }

    public Inventorytable(int documentCode, int line, int productCode, int price, int quantity, int newQuantity) {
       this.documentCode = documentCode;
       this.line = line;
       this.productCode = productCode;
       this.price = price;
       this.quantity = quantity;
       this.newQuantity = newQuantity;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public int getDocumentCode() {
        return this.documentCode;
    }
    
    public void setDocumentCode(int documentCode) {
        this.documentCode = documentCode;
    }
    public int getLine() {
        return this.line;
    }
    
    public void setLine(int line) {
        this.line = line;
    }
    public int getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(int productCode) {
        this.productCode = productCode;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getNewQuantity() {
        return this.newQuantity;
    }
    
    public void setNewQuantity(int newQuantity) {
        this.newQuantity = newQuantity;
    }




}


