package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Inventory generated by hbm2java
 */
public class Inventory  implements java.io.Serializable {


     private Integer code;
     private String number;
     private Date datetime;
     private Integer employeeCode;
     private Integer incomingCode;
     private Integer outcomingCode;
     private int locked;
     private int active;

    public Inventory() {
    }

	
    public Inventory(int locked, int active) {
        this.locked = locked;
        this.active = active;
    }
    public Inventory(String number, Date datetime, Integer employeeCode, Integer incomingCode, Integer outcomingCode, int locked, int active) {
       this.number = number;
       this.datetime = datetime;
       this.employeeCode = employeeCode;
       this.incomingCode = incomingCode;
       this.outcomingCode = outcomingCode;
       this.locked = locked;
       this.active = active;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Integer getEmployeeCode() {
        return this.employeeCode;
    }
    
    public void setEmployeeCode(Integer employeeCode) {
        this.employeeCode = employeeCode;
    }
    public Integer getIncomingCode() {
        return this.incomingCode;
    }
    
    public void setIncomingCode(Integer incomingCode) {
        this.incomingCode = incomingCode;
    }
    public Integer getOutcomingCode() {
        return this.outcomingCode;
    }
    
    public void setOutcomingCode(Integer outcomingCode) {
        this.outcomingCode = outcomingCode;
    }
    public int getLocked() {
        return this.locked;
    }
    
    public void setLocked(int locked) {
        this.locked = locked;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


