package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA



/**
 * Nomenclature generated by hbm2java
 */
public class Nomenclature  implements java.io.Serializable {


     private Integer code;
     private String name;
     private String unit;
     private Integer price;
     private Integer inPrice;
     private Integer quantity;
     private double weight;
     private String scanCode;
     private String warranty;
     private int active;

    public Nomenclature() {
    }

	
    public Nomenclature(String name, double weight, int active) {
        this.name = name;
        this.weight = weight;
        this.active = active;
    }
    public Nomenclature(String name, String unit, Integer price, Integer inPrice, Integer quantity, double weight, String scanCode, String warranty, int active) {
       this.name = name;
       this.unit = unit;
       this.price = price;
       this.inPrice = inPrice;
       this.quantity = quantity;
       this.weight = weight;
       this.scanCode = scanCode;
       this.warranty = warranty;
       this.active = active;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Integer getInPrice() {
        return this.inPrice;
    }
    
    public void setInPrice(Integer inPrice) {
        this.inPrice = inPrice;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public double getWeight() {
        return this.weight;
    }
    
    public void setWeight(double weight) {
        this.weight = weight;
    }
    public String getScanCode() {
        return this.scanCode;
    }
    
    public void setScanCode(String scanCode) {
        this.scanCode = scanCode;
    }
    public String getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(String warranty) {
        this.warranty = warranty;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


