package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Outcoming generated by hbm2java
 */
public class Outcoming  implements java.io.Serializable {


     private Integer code;
     private Date datetime;
     private String number;
     private int documentType;
     private String invoiceNumber;
     private Date invoiceDate;
     private String tnnumber;
     private Integer contractor;
     private Integer employee;
     private Integer athorizer;
     private String contractNumber;
     private Date contractDate;
     private String auto;
     private String trailer;
     private String owner;
     private String driver;
     private String loadingAddress;
     private String unloadingAddress;
     private String recepient;
     private String recepientName;
     private String warrant;
     private String warrantOrganization;
     private String note;
     private int flag;
     private int locked;
     private int active;

    public Outcoming() {
    }

	
    public Outcoming(int documentType, int flag, int locked, int active) {
        this.documentType = documentType;
        this.flag = flag;
        this.locked = locked;
        this.active = active;
    }
    public Outcoming(Date datetime, String number, int documentType, String invoiceNumber, Date invoiceDate, String tnnumber, Integer contractor, Integer employee, Integer athorizer, String contractNumber, Date contractDate, String auto, String trailer, String owner, String driver, String loadingAddress, String unloadingAddress, String recepient, String recepientName, String warrant, String warrantOrganization, String note, int flag, int locked, int active) {
       this.datetime = datetime;
       this.number = number;
       this.documentType = documentType;
       this.invoiceNumber = invoiceNumber;
       this.invoiceDate = invoiceDate;
       this.tnnumber = tnnumber;
       this.contractor = contractor;
       this.employee = employee;
       this.athorizer = athorizer;
       this.contractNumber = contractNumber;
       this.contractDate = contractDate;
       this.auto = auto;
       this.trailer = trailer;
       this.owner = owner;
       this.driver = driver;
       this.loadingAddress = loadingAddress;
       this.unloadingAddress = unloadingAddress;
       this.recepient = recepient;
       this.recepientName = recepientName;
       this.warrant = warrant;
       this.warrantOrganization = warrantOrganization;
       this.note = note;
       this.flag = flag;
       this.locked = locked;
       this.active = active;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public int getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(int documentType) {
        this.documentType = documentType;
    }
    public String getInvoiceNumber() {
        return this.invoiceNumber;
    }
    
    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public String getTnnumber() {
        return this.tnnumber;
    }
    
    public void setTnnumber(String tnnumber) {
        this.tnnumber = tnnumber;
    }
    public Integer getContractor() {
        return this.contractor;
    }
    
    public void setContractor(Integer contractor) {
        this.contractor = contractor;
    }
    public Integer getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Integer employee) {
        this.employee = employee;
    }
    public Integer getAthorizer() {
        return this.athorizer;
    }
    
    public void setAthorizer(Integer athorizer) {
        this.athorizer = athorizer;
    }
    public String getContractNumber() {
        return this.contractNumber;
    }
    
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }
    public Date getContractDate() {
        return this.contractDate;
    }
    
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }
    public String getAuto() {
        return this.auto;
    }
    
    public void setAuto(String auto) {
        this.auto = auto;
    }
    public String getTrailer() {
        return this.trailer;
    }
    
    public void setTrailer(String trailer) {
        this.trailer = trailer;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getDriver() {
        return this.driver;
    }
    
    public void setDriver(String driver) {
        this.driver = driver;
    }
    public String getLoadingAddress() {
        return this.loadingAddress;
    }
    
    public void setLoadingAddress(String loadingAddress) {
        this.loadingAddress = loadingAddress;
    }
    public String getUnloadingAddress() {
        return this.unloadingAddress;
    }
    
    public void setUnloadingAddress(String unloadingAddress) {
        this.unloadingAddress = unloadingAddress;
    }
    public String getRecepient() {
        return this.recepient;
    }
    
    public void setRecepient(String recepient) {
        this.recepient = recepient;
    }
    public String getRecepientName() {
        return this.recepientName;
    }
    
    public void setRecepientName(String recepientName) {
        this.recepientName = recepientName;
    }
    public String getWarrant() {
        return this.warrant;
    }
    
    public void setWarrant(String warrant) {
        this.warrant = warrant;
    }
    public String getWarrantOrganization() {
        return this.warrantOrganization;
    }
    
    public void setWarrantOrganization(String warrantOrganization) {
        this.warrantOrganization = warrantOrganization;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public int getFlag() {
        return this.flag;
    }
    
    public void setFlag(int flag) {
        this.flag = flag;
    }
    public int getLocked() {
        return this.locked;
    }
    
    public void setLocked(int locked) {
        this.locked = locked;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


