package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA



/**
 * Previousbalance generated by hbm2java
 */
public class Previousbalance  implements java.io.Serializable {


     private Integer code;
     private Integer year;
     private Integer quarter;
     private Integer amount;

    public Previousbalance() {
    }

    public Previousbalance(Integer year, Integer quarter, Integer amount) {
       this.year = year;
       this.quarter = quarter;
       this.amount = amount;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getQuarter() {
        return this.quarter;
    }
    
    public void setQuarter(Integer quarter) {
        this.quarter = quarter;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }




}


