package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Register generated by hbm2java
 */
public class Register  implements java.io.Serializable {


     private Integer code;
     private Date datetime;
     private Integer documentType;
     private String number;
     private String supplement;
     private Integer employeeCode;
     private Integer amount;
     private String paymentType;
     private String corrAccount;
     private String announcementNumber;
     private String reportingCode;
     private String page;
     private int locked;
     private Integer active;

    public Register() {
    }

	
    public Register(int locked) {
        this.locked = locked;
    }
    public Register(Date datetime, Integer documentType, String number, String supplement, Integer employeeCode, Integer amount, String paymentType, String corrAccount, String announcementNumber, String reportingCode, String page, int locked, Integer active) {
       this.datetime = datetime;
       this.documentType = documentType;
       this.number = number;
       this.supplement = supplement;
       this.employeeCode = employeeCode;
       this.amount = amount;
       this.paymentType = paymentType;
       this.corrAccount = corrAccount;
       this.announcementNumber = announcementNumber;
       this.reportingCode = reportingCode;
       this.page = page;
       this.locked = locked;
       this.active = active;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Integer getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(Integer documentType) {
        this.documentType = documentType;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getSupplement() {
        return this.supplement;
    }
    
    public void setSupplement(String supplement) {
        this.supplement = supplement;
    }
    public Integer getEmployeeCode() {
        return this.employeeCode;
    }
    
    public void setEmployeeCode(Integer employeeCode) {
        this.employeeCode = employeeCode;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }
    public String getCorrAccount() {
        return this.corrAccount;
    }
    
    public void setCorrAccount(String corrAccount) {
        this.corrAccount = corrAccount;
    }
    public String getAnnouncementNumber() {
        return this.announcementNumber;
    }
    
    public void setAnnouncementNumber(String announcementNumber) {
        this.announcementNumber = announcementNumber;
    }
    public String getReportingCode() {
        return this.reportingCode;
    }
    
    public void setReportingCode(String reportingCode) {
        this.reportingCode = reportingCode;
    }
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }
    public int getLocked() {
        return this.locked;
    }
    
    public void setLocked(int locked) {
        this.locked = locked;
    }
    public Integer getActive() {
        return this.active;
    }
    
    public void setActive(Integer active) {
        this.active = active;
    }




}


