package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA



/**
 * Registertable generated by hbm2java
 */
public class Registertable  implements java.io.Serializable {


     private Integer code;
     private int number;
     private String unt;
     private Integer productCode;

    public Registertable() {
    }

	
    public Registertable(int number) {
        this.number = number;
    }
    public Registertable(int number, String unt, Integer productCode) {
       this.number = number;
       this.unt = unt;
       this.productCode = productCode;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public String getUnt() {
        return this.unt;
    }
    
    public void setUnt(String unt) {
        this.unt = unt;
    }
    public Integer getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }




}


