package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA



/**
 * Services generated by hbm2java
 */
public class Services  implements java.io.Serializable {


     private Integer code;
     private String name;
     private String unit;
     private int price;
     private int active;

    public Services() {
    }

	
    public Services(int price, int active) {
        this.price = price;
        this.active = active;
    }
    public Services(String name, String unit, int price, int active) {
       this.name = name;
       this.unit = unit;
       this.price = price;
       this.active = active;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


