package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Suppliers generated by hbm2java
 */
public class Suppliers  implements java.io.Serializable {


     private Integer code;
     private String contractNumber;
     private Date contractDate;
     private String name;
     private String address;
     private String account;
     private String unt;
     private Integer bank;
     private String note;
     private int locked;
     private int active;

    public Suppliers() {
    }

	
    public Suppliers(String note, int locked, int active) {
        this.note = note;
        this.locked = locked;
        this.active = active;
    }
    public Suppliers(String contractNumber, Date contractDate, String name, String address, String account, String unt, Integer bank, String note, int locked, int active) {
       this.contractNumber = contractNumber;
       this.contractDate = contractDate;
       this.name = name;
       this.address = address;
       this.account = account;
       this.unt = unt;
       this.bank = bank;
       this.note = note;
       this.locked = locked;
       this.active = active;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getContractNumber() {
        return this.contractNumber;
    }
    
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }
    public Date getContractDate() {
        return this.contractDate;
    }
    
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }
    public String getUnt() {
        return this.unt;
    }
    
    public void setUnt(String unt) {
        this.unt = unt;
    }
    public Integer getBank() {
        return this.bank;
    }
    
    public void setBank(Integer bank) {
        this.bank = bank;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public int getLocked() {
        return this.locked;
    }
    
    public void setLocked(int locked) {
        this.locked = locked;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


