package sales.entity;
// Generated 25.03.2014 13:42:31 by Hibernate Tools 3.2.1.GA



/**
 * Transports generated by hbm2java
 */
public class Transports  implements java.io.Serializable {


     private Integer code;
     private String auto;
     private String trailer;
     private String owner;
     private String driver;
     private int active;

    public Transports() {
    }

	
    public Transports(int active) {
        this.active = active;
    }
    public Transports(String auto, String trailer, String owner, String driver, int active) {
       this.auto = auto;
       this.trailer = trailer;
       this.owner = owner;
       this.driver = driver;
       this.active = active;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getAuto() {
        return this.auto;
    }
    
    public void setAuto(String auto) {
        this.auto = auto;
    }
    public String getTrailer() {
        return this.trailer;
    }
    
    public void setTrailer(String trailer) {
        this.trailer = trailer;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getDriver() {
        return this.driver;
    }
    
    public void setDriver(String driver) {
        this.driver = driver;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


