/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShipmentsView.java
 *
 * Created on 19.05.2011, 11:11:06
 */
package sales.outcoming;

import sales.interfaces.IOutcoming;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import org.hibernate.classic.Session;
import org.jdesktop.application.Action;
import sales.SalesApp;
import sales.SalesView;
import sales.entity.Incoming;
import sales.interfaces.IClose;
import sales.util.HUtil;
import sales.util.Util;

/**
 *
 * @author Администратор
 */
public class ShipmentsView extends javax.swing.JInternalFrame implements IClose {

    static Logger logger = Logger.getLogger(SalesApp.class.getName());

    /** Creates new form ShipmentsView */
    public ShipmentsView(IOutcoming parent, SalesView salesView, int productCode, int row) {
        initComponents();

        Util.initJIF(this, "Партии", parent, salesView);
        Util.initJTable(jtShipments);

        this.parent = parent;
        this.salesView = salesView;
        this.productCode = productCode;
        this.row = row;

        setLocation((salesView.getFrame().getWidth() - getWidth()) / 2,
                (salesView.getFrame().getHeight() - getHeight()) / 2);

        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Код");
        tableHeaders.add("Номер");
        tableHeaders.add("Дата");
        tableHeaders.add("Кол-во");
        tableHeaders.add("Цена");

        SimpleDateFormat sdfd = new SimpleDateFormat("dd.MM.yyyy");

        List ss = HUtil.getShipments(productCode, Calendar.getInstance().getTime());

        Session session = HUtil.getSession();

        for (int j = 0; j < ss.size(); j++) {
            HashMap se = (HashMap) ss.get(j);
            Vector<Object> oneRow = new Vector<Object>();
            Incoming i = (Incoming) HUtil.getElement("Incoming", (Integer) se.get("incomingCode"), session);
            if (i != null) {
                oneRow.add(i.getCode());
                oneRow.add(i.getNumber());
                oneRow.add(sdfd.format(i.getDatetime()));
                oneRow.add(se.get("balance"));
                oneRow.add(se.get("price"));
                tableData.add(oneRow);
            }
        }

        session.close();

        jtShipments.setModel(new MyTableModel(tableData, tableHeaders));
        Util.autoResizeColWidth(jtShipments);

    }

    private class MyTableModel extends DefaultTableModel {

        public MyTableModel(Vector table, Vector header) {
            super(table, header);
        }

        @Override
        public boolean isCellEditable(int r, int c) {
            return false;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtShipments = new javax.swing.JTable();
        jbOK = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sales.SalesApp.class).getContext().getResourceMap(ShipmentsView.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setClosable(true);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jtShipments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtShipments.setFillsViewportHeight(true);
        jtShipments.setName("jtShipments"); // NOI18N
        jtShipments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtShipmentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtShipments);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sales.SalesApp.class).getContext().getActionMap(ShipmentsView.class, this);
        jbOK.setAction(actionMap.get("jbOK")); // NOI18N
        jbOK.setText(resourceMap.getString("jbOK.text")); // NOI18N
        jbOK.setName("jbOK"); // NOI18N

        jbCancel.setAction(actionMap.get("jbCancel")); // NOI18N
        jbCancel.setText(resourceMap.getString("jbCancel.text")); // NOI18N
        jbCancel.setName("jbCancel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOK)
                    .addComponent(jbCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtShipmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtShipmentsMouseClicked
        if (evt.getClickCount() > 1) {
            jbOK();
        }
    }//GEN-LAST:event_jtShipmentsMouseClicked

    public void close() {
    }

    @Action
    public void jbCancel() {
        Util.closeJIF(this, parent, salesView);
        Util.closeJIFTab(this, salesView);
    }

    @Action
    public void jbOK() {
        if (jtShipments.getSelectedRow() != -1) {
            parent.setIncomingItem(
                    new Integer(jtShipments.getModel().getValueAt(jtShipments.getSelectedRow(), 0).toString()), row);
            parent.fixQuantity(
                    productCode,
                    new Integer(jtShipments.getModel().getValueAt(jtShipments.getSelectedRow(), 0).toString()),
                    row);
        }
        Util.closeJIF(this, parent, salesView);
        Util.closeJIFTab(this, salesView);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    private javax.swing.JTable jtShipments;
    // End of variables declaration//GEN-END:variables
    private IOutcoming parent;
    private SalesView salesView;
    private int productCode;
    private int row;
}
