package sales.util;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import org.hibernate.classic.Session;
import org.jdesktop.application.Action;
import sales.interfaces.IInit;
import sales.SalesApp;
import sales.entity.Constants;
import sales.entity.Registertable;

public class InitView extends javax.swing.JDialog {

    static Logger logger = Logger.getLogger(SalesApp.class.getName());

    /** Creates new form FirstTime */
    public InitView(String ac, IInit init, String journalName) {
        super(new JFrame(), true);
        initComponents();

        this.ac = ac;
        this.journalName = journalName;

        this.init = init;
        init.setStatus(false);

        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dThis = this.getSize();
        setLocation(new Point((int) (d.getWidth() - dThis.getWidth()) / 2, (int) (d.getHeight() - dThis.getHeight()) / 2));

        jlAuthorizationCode.setText(ac);

        jtfNds.addKeyListener(new KeyAdapter() {

            @Override
            public void keyTyped(KeyEvent e) {
                jtfNds.setEditable(
                        Character.isDigit(e.getKeyChar()) || e.getKeyChar() == KeyEvent.VK_BACK_SPACE);
            }
        });

        jtfName.setText(HUtil.getConstant("name"));
        jtfUnt.setText(HUtil.getConstant("unt"));
        jtfAddress.setText(HUtil.getConstant("address"));
        jtfLegalAddress.setText(HUtil.getConstant("legalAddress"));
        jtfBank.setText(HUtil.getConstant("bank"));
        jtfBankCode.setText(HUtil.getConstant("bankCode"));
        jtfAccount.setText(HUtil.getConstant("account"));
        jtfDirector.setText(HUtil.getShortNameByCode(HUtil.getIntConstant("director")));
        jtfChiefAccountant.setText(HUtil.getShortNameByCode(HUtil.getIntConstant("chiefAccountant")));
        jtfCashier.setText(HUtil.getShortNameByCode(HUtil.getIntConstant("cashier")));
        jtfNds.setText(HUtil.getConstant("nds"));
        jtfEmail.setText(HUtil.getConstant("email"));
        jtfSmtp.setText(HUtil.getConstant("smtp"));
        jtfSmtpPort.setText(HUtil.getConstant("smtpPort"));
        jtfSmtpLogin.setText(HUtil.getConstant("smtpLogin"));
        jtfSmtpPassword.setText(HUtil.getConstant("smtpPassword"));

        String lck = HUtil.getConstant("lock");
        if (lck == null || !lck.equals("locked")) {
            lock = 0;
        } else {
            lock = 1;
            JOptionPane.showMessageDialog(
                    this,
                    "Константы редактируются другим пользователем и будут открыты только для просмотра!",
                    "Блокировка", JOptionPane.PLAIN_MESSAGE);

            jtfName.setEditable(false);
            jtfUnt.setEditable(false);
            jtfAddress.setEditable(false);
            jtfLegalAddress.setEditable(false);
            jtfBank.setEditable(false);
            jtfBankCode.setEditable(false);
            jtfAccount.setEditable(false);
            jtfDirector.setEditable(false);
            jtfChiefAccountant.setEditable(false);
            jtfCashier.setEditable(false);
            jtfNds.setEditable(false);
            jtfEmail.setEditable(false);
            jtfSmtp.setEditable(false);
            jtfSmtpPort.setEditable(false);
            jtfSmtpLogin.setEditable(false);
            jtfSmtpPassword.setEditable(false);

        }
        ArrayList consts = new ArrayList();
        consts.add(new Constants("lock", "", "locked"));
        HUtil.setConstants(consts);

        addWindowListener(new MyWindowAdapter());

        hash = Util.hash(this);

    }

    private class MyWindowAdapter extends WindowAdapter {

        public void windowClosing(WindowEvent e) {
            save();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jtfSmtpLogin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfSmtpPassword = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfSmtp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfSmtpPort = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfUnt = new javax.swing.JTextField();
        jtfAddress = new javax.swing.JTextField();
        jtfLegalAddress = new javax.swing.JTextField();
        jtfBank = new javax.swing.JTextField();
        jtfBankCode = new javax.swing.JTextField();
        jtfAccount = new javax.swing.JTextField();
        jtfDirector = new javax.swing.JTextField();
        jtfChiefAccountant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfCashier = new javax.swing.JTextField();
        jlAddress = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfNds = new javax.swing.JTextField();
        jbRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlAuthorizationCode = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtfActivationCode = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jbClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sales.SalesApp.class).getContext().getResourceMap(InitView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jtfSmtpLogin.setName("jtfSmtpLogin"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jtfSmtpPassword.setName("jtfSmtpPassword"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jtfSmtp.setName("jtfSmtp"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jtfSmtpPort.setName("jtfSmtpPort"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jtfName.setName("jtfName"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setForeground(resourceMap.getColor("jLabel17.foreground")); // NOI18N
        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jtfUnt.setName("jtfUnt"); // NOI18N

        jtfAddress.setName("jtfAddress"); // NOI18N

        jtfLegalAddress.setName("jtfLegalAddress"); // NOI18N

        jtfBank.setName("jtfBank"); // NOI18N

        jtfBankCode.setName("jtfBankCode"); // NOI18N

        jtfAccount.setName("jtfAccount"); // NOI18N

        jtfDirector.setName("jtfDirector"); // NOI18N

        jtfChiefAccountant.setName("jtfChiefAccountant"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jtfCashier.setName("jtfCashier"); // NOI18N

        jlAddress.setText(resourceMap.getString("jlAddress.text")); // NOI18N
        jlAddress.setName("jlAddress"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jtfEmail.setName("jtfEmail"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jtfNds.setName("jtfNds"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sales.SalesApp.class).getContext().getActionMap(InitView.class, this);
        jbRegister.setAction(actionMap.get("register")); // NOI18N
        jbRegister.setText(resourceMap.getString("jbRegister.text")); // NOI18N
        jbRegister.setName("jbRegister"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        jlAuthorizationCode.setFont(resourceMap.getFont("jlAuthorizationCode.font")); // NOI18N
        jlAuthorizationCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAuthorizationCode.setName("jlAuthorizationCode"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAuthorizationCode, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAuthorizationCode, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setName("jLabel20"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setName("jPanel2"); // NOI18N

        jtfActivationCode.setFont(resourceMap.getFont("jtfActivationCode.font")); // NOI18N
        jtfActivationCode.setText(resourceMap.getString("jtfActivationCode.text")); // NOI18N
        jtfActivationCode.setName("jtfActivationCode"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfActivationCode, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfActivationCode, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel21.setFont(resourceMap.getFont("jLabel21.font")); // NOI18N
        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setFont(resourceMap.getFont("jLabel22.font")); // NOI18N
        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        jbClose.setAction(actionMap.get("exitFalse")); // NOI18N
        jbClose.setText(resourceMap.getString("jbClose.text")); // NOI18N
        jbClose.setName("jbClose"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jlAddress)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfNds, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                .addGap(377, 377, 377))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfUnt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addGap(292, 292, 292))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(281, 281, 281))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfSmtpPort, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                .addGap(377, 377, 377))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfSmtpPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(jtfSmtpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(jtfSmtp, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(jtfCashier, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(jtfChiefAccountant, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(jtfDirector, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(jtfBankCode, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(jtfBank, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(jtfLegalAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(jtfAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLegalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBankCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfChiefAccountant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSmtpPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSmtpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSmtpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel20))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbClose)
                    .addComponent(jbRegister))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbRegister;
    private javax.swing.JLabel jlAddress;
    private javax.swing.JLabel jlAuthorizationCode;
    private javax.swing.JTextField jtfAccount;
    private javax.swing.JTextField jtfActivationCode;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfBank;
    private javax.swing.JTextField jtfBankCode;
    private javax.swing.JTextField jtfCashier;
    private javax.swing.JTextField jtfChiefAccountant;
    private javax.swing.JTextField jtfDirector;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfLegalAddress;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfNds;
    private javax.swing.JTextField jtfSmtp;
    private javax.swing.JTextField jtfSmtpLogin;
    private javax.swing.JTextField jtfSmtpPassword;
    private javax.swing.JTextField jtfSmtpPort;
    private javax.swing.JTextField jtfUnt;
    // End of variables declaration//GEN-END:variables
    private Integer hash;
    private Integer lock;
    private IInit init;
    private String ac;
    private String journalName;

    private void save() {
        if (lock == 0) {
            ArrayList consts = new ArrayList();
            if (hash == null || !hash.equals(Util.hash(this))) {
                consts.add(new Constants("name", "", jtfName.getText()));
                consts.add(new Constants("unt", "", jtfUnt.getText()));
                consts.add(new Constants("address", "", jtfAddress.getText()));
                consts.add(new Constants("legalAddress", "", jtfLegalAddress.getText()));
                consts.add(new Constants("bank", "", jtfBank.getText()));
                consts.add(new Constants("bankCode", "", jtfBankCode.getText()));
                consts.add(new Constants("account", "", jtfAccount.getText()));
                consts.add(new Constants("director", "", jtfDirector.getText()));
                consts.add(new Constants("chiefAccountant", "", jtfChiefAccountant.getText()));
                consts.add(new Constants("cashier", "", jtfCashier.getText()));
                consts.add(new Constants("nds", "", jtfNds.getText()));
                consts.add(new Constants("email", "", jtfEmail.getText()));
                consts.add(new Constants("smtp", "", jtfSmtp.getText()));
                consts.add(new Constants("smtpPort", "", jtfSmtpPort.getText()));
                consts.add(new Constants("smtpLogin", "", jtfSmtpLogin.getText()));
                consts.add(new Constants("smtpPassword", "", jtfSmtpPassword.getText()));
            }
            consts.add(new Constants("lock", "", ""));
            HUtil.setConstants(consts);
        }
    }

    public void close() {
        save();
    }

    @Action
    public void register() {

        if (lock == 0 && (hash == null || !hash.equals(Util.hash(this)))) {
            if (!jtfName.getText().trim().isEmpty() && !jtfUnt.getText().trim().isEmpty()) {
                save();
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Наименование организации и УНН не могут быть пустыми!",
                        "Ошибка сохранения констант",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            save();
        }

        try {

            String u = Util.removeSpacesStr(jtfUnt.getText());
            byte[] du = u.getBytes();

            byte[] d2 = new byte[8 + du.length];
            for (int i = 0; i < 8; i++) {
                d2[i] = (byte) Integer.parseInt(ac.substring(i, i + 1));
            }
            for (int i = 0; i < du.length; i++) {
                d2[8 + i] = du[i];
            }

            byte[] d3 = MessageDigest.getInstance("MD5").digest(d2);

            String ca = "";
            String rc = jtfActivationCode.getText();
            if (rc.length() == 8) {
                for (int i = 0; i < 8; i++) {
                    int sm = 0;
                    for (int j = 0; j < 1; j++) {
                        sm += d3[i * 2 + j];
                    }
                    if (sm < 0) {
                        sm = -sm;
                    }
                    ca += sm % 10;
                }
                if (ca.equals(rc)) {
                    Session session = HUtil.getSession();
                    List res = HUtil.executeHql(
                            "from Registertable r where r.unt = '" + jlAuthorizationCode.getText() + "' order by r.number");
                    if (res != null) {
                        session.beginTransaction();
                        for (int i = 0; i < res.size(); i++) {
                            Registertable r = (Registertable) res.get(i);
                            session.delete(r);
                        }
                        session.getTransaction().commit();
                    }
                    session.beginTransaction();
                    for (int i = 0; i < d3.length; i++) {
                        Registertable r = new Registertable();
                        r.setNumber(i);
                        r.setUnt(jlAuthorizationCode.getText());
                        r.setProductCode((int) d3[i]);
                        session.save(r);
                    }
                    session.getTransaction().commit();
                    session.close();
                    JOptionPane.showMessageDialog(this, "Спасибо за регистрацию!", "Регистрация", JOptionPane.PLAIN_MESSAGE);
                    init.setStatus(true);

                    dispose();

                    return;
                }
            }
            JOptionPane.showMessageDialog(null, "Неверный код активации", "Ошибка активации", JOptionPane.ERROR_MESSAGE);
            checkDocs();
        } catch (Exception e) {
            logger.error(e);
        }
    }

    private void checkDocs() {
        if (journalName != null) {
            List res = HUtil.executeHql("from " + journalName);
            if (res == null || res.size() <= 10) {
                init.setStatus(true);
            } else {
                JOptionPane.showMessageDialog(null, "Превышено количество создаваемых документов для пробной версии!", "Ошибка активации", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    @Action
    public void exitFalse() {
        save();
        checkDocs();
        dispose();
    }
}
